-- Every text column uses the "C" collation (code point order, as SQLite's BINARY did), so sorting and comparing
-- merchants, names, dates and ISO timestamps behaves the same on PGlite and on any Postgres server whatever its
-- default locale. drizzle-kit does not track collations: add COLLATE "C" by hand to text columns of new migrations.
CREATE TABLE "account_balance_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_balance_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"as_of" text COLLATE "C" NOT NULL,
	"balance_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"source" text COLLATE "C" NOT NULL,
	"raw" jsonb,
	"created_at" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text COLLATE "C" NOT NULL,
	"kind" text COLLATE "C" NOT NULL,
	"institution" text COLLATE "C",
	"last4" text COLLATE "C",
	"currency" text COLLATE "C" NOT NULL,
	"starting_balance_minor" bigint,
	"starting_balance_on" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bank_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bank_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"connection_id" integer NOT NULL,
	"provider_account_id" text COLLATE "C" NOT NULL,
	"account_id" integer NOT NULL,
	"name" text COLLATE "C" NOT NULL,
	"type" text COLLATE "C" NOT NULL,
	"subtype" text COLLATE "C",
	"last_four" text COLLATE "C",
	"currency" text COLLATE "C" NOT NULL,
	"cursor" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bank_connections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bank_connections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"provider" text COLLATE "C" NOT NULL,
	"kind" text COLLATE "C" DEFAULT 'bank' NOT NULL,
	"enrollment_id" text COLLATE "C" NOT NULL,
	"institution_name" text COLLATE "C",
	"access_token" text COLLATE "C" NOT NULL,
	"status" text COLLATE "C" DEFAULT 'active' NOT NULL,
	"last_error" text COLLATE "C",
	"last_synced_at" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL,
	"cursor" text COLLATE "C"
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text COLLATE "C" NOT NULL,
	"kind" text COLLATE "C" NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"sort" integer DEFAULT 0 NOT NULL,
	"archived_at" text COLLATE "C"
);
--> statement-breakpoint
CREATE TABLE "counterparty_ignores" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "counterparty_ignores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"kind" text COLLATE "C" NOT NULL,
	"normalized" text COLLATE "C" NOT NULL,
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "holding_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "holding_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"investment_account_id" integer NOT NULL,
	"security_id" integer,
	"position_key" text COLLATE "C" NOT NULL,
	"as_of" text COLLATE "C" NOT NULL,
	"quantity" text COLLATE "C" NOT NULL,
	"price" text COLLATE "C" NOT NULL,
	"market_value_minor" bigint NOT NULL,
	"cost_basis_minor" bigint,
	"currency" text COLLATE "C" NOT NULL,
	"source_raw" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_batches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"source" text COLLATE "C" NOT NULL,
	"file_name" text COLLATE "C" NOT NULL,
	"file_hash" text COLLATE "C" NOT NULL,
	"rows_total" integer DEFAULT 0 NOT NULL,
	"rows_inserted" integer DEFAULT 0 NOT NULL,
	"rows_skipped_dup" integer DEFAULT 0 NOT NULL,
	"rows_linked" integer DEFAULT 0 NOT NULL,
	"declared" jsonb,
	"parsed" jsonb,
	"status" text COLLATE "C" DEFAULT 'committed' NOT NULL,
	"created_at" text COLLATE "C" NOT NULL,
	"reverted_at" text COLLATE "C"
);
--> statement-breakpoint
CREATE TABLE "investment_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "investment_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"provider" text COLLATE "C" NOT NULL,
	"external_id" text COLLATE "C" NOT NULL,
	"bank_connection_id" integer,
	"name" text COLLATE "C" NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investment_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "investment_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"investment_account_id" integer NOT NULL,
	"security_id" integer,
	"external_id" text COLLATE "C" NOT NULL,
	"date" text COLLATE "C" NOT NULL,
	"type" text COLLATE "C" NOT NULL,
	"quantity" text COLLATE "C",
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"description" text COLLATE "C",
	"raw" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text COLLATE "C" NOT NULL,
	"cursor" text COLLATE "C",
	"status" text COLLATE "C" DEFAULT 'idle' NOT NULL,
	"run_after" text COLLATE "C",
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text COLLATE "C",
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "merchant_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "merchant_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"merchant" text COLLATE "C" NOT NULL,
	"category_id" integer,
	"participant_ids" jsonb,
	"auto_split" boolean DEFAULT false NOT NULL,
	"suggest" boolean DEFAULT true NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monthly_targets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monthly_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"month" text COLLATE "C",
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participant_identities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "participant_identities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"participant_id" integer NOT NULL,
	"kind" text COLLATE "C" NOT NULL,
	"value" text COLLATE "C" NOT NULL,
	"normalized" text COLLATE "C" NOT NULL,
	"source" text COLLATE "C" DEFAULT 'manual' NOT NULL,
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "participants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text COLLATE "C" NOT NULL,
	"is_self" boolean DEFAULT false NOT NULL,
	"aliases" text COLLATE "C" DEFAULT '[]' NOT NULL,
	"archived_at" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plaid_link_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plaid_link_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"link_token" text COLLATE "C" NOT NULL,
	"environment" text COLLATE "C" NOT NULL,
	"purpose" text COLLATE "C" NOT NULL,
	"kind" text COLLATE "C" DEFAULT 'bank' NOT NULL,
	"connection_id" integer,
	"status" text COLLATE "C" DEFAULT 'open' NOT NULL,
	"link_session_id" text COLLATE "C",
	"exchanged" jsonb,
	"created_at" text COLLATE "C" NOT NULL,
	"checked_at" text COLLATE "C",
	"last_error" text COLLATE "C"
);
--> statement-breakpoint
CREATE TABLE "securities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "securities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"provider" text COLLATE "C" NOT NULL,
	"external_id" text COLLATE "C" NOT NULL,
	"symbol" text COLLATE "C",
	"name" text COLLATE "C",
	"type" text COLLATE "C",
	"currency" text COLLATE "C" NOT NULL,
	"isin" text COLLATE "C",
	"cusip" text COLLATE "C",
	"multiplier" text COLLATE "C",
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settlement_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "settlement_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"settlement_id" integer NOT NULL,
	"transaction_id" integer NOT NULL,
	"participant_id" integer NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settlements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "settlements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"participant_id" integer NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"original_amount_minor" bigint,
	"original_currency" text COLLATE "C",
	"fx_rate" text COLLATE "C",
	"settled_on" text COLLATE "C" NOT NULL,
	"note" text COLLATE "C",
	"transaction_id" integer,
	"kind" text COLLATE "C" DEFAULT 'payment' NOT NULL,
	"prior_kind" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transaction_splits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transaction_splits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"transaction_id" integer NOT NULL,
	"participant_id" integer NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"owed_minor" bigint NOT NULL,
	"paid_minor" bigint DEFAULT 0 NOT NULL,
	"method" text COLLATE "C" NOT NULL,
	"created_at" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"account_id" integer,
	"occurred_at" text COLLATE "C" NOT NULL,
	"occurred_on" text COLLATE "C" DEFAULT '' NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"original_amount_minor" bigint,
	"original_currency" text COLLATE "C",
	"kind" text COLLATE "C" NOT NULL,
	"counterparty_raw" text COLLATE "C" DEFAULT '' NOT NULL,
	"description_raw" text COLLATE "C" DEFAULT '' NOT NULL,
	"merchant" text COLLATE "C" DEFAULT '' NOT NULL,
	"category_id" integer,
	"note" text COLLATE "C",
	"shared_note" text COLLATE "C",
	"source" text COLLATE "C" NOT NULL,
	"source_ref" text COLLATE "C",
	"source_category" text COLLATE "C",
	"payment_method" text COLLATE "C",
	"raw" jsonb,
	"import_batch_id" integer,
	"dedup_key" text COLLATE "C" NOT NULL,
	"duplicate_of_id" integer,
	"status" text COLLATE "C" DEFAULT 'ok' NOT NULL,
	"user_edited_at" text COLLATE "C",
	"split_suggestion_dismissed_at" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"key" text COLLATE "C" NOT NULL,
	"value" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_balance_snapshots" ADD CONSTRAINT "account_balance_snapshots_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_accounts" ADD CONSTRAINT "bank_accounts_connection_id_bank_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."bank_connections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_accounts" ADD CONSTRAINT "bank_accounts_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "holding_snapshots" ADD CONSTRAINT "holding_snapshots_investment_account_id_investment_accounts_id_fk" FOREIGN KEY ("investment_account_id") REFERENCES "public"."investment_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "holding_snapshots" ADD CONSTRAINT "holding_snapshots_security_id_securities_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."securities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investment_accounts" ADD CONSTRAINT "investment_accounts_bank_connection_id_bank_connections_id_fk" FOREIGN KEY ("bank_connection_id") REFERENCES "public"."bank_connections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investment_transactions" ADD CONSTRAINT "investment_transactions_investment_account_id_investment_accounts_id_fk" FOREIGN KEY ("investment_account_id") REFERENCES "public"."investment_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investment_transactions" ADD CONSTRAINT "investment_transactions_security_id_securities_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."securities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_rules" ADD CONSTRAINT "merchant_rules_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participant_identities" ADD CONSTRAINT "participant_identities_participant_id_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plaid_link_sessions" ADD CONSTRAINT "plaid_link_sessions_connection_id_bank_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."bank_connections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlement_items" ADD CONSTRAINT "settlement_items_settlement_id_settlements_id_fk" FOREIGN KEY ("settlement_id") REFERENCES "public"."settlements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlement_items" ADD CONSTRAINT "settlement_items_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlement_items" ADD CONSTRAINT "settlement_items_participant_id_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_participant_id_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transaction_splits" ADD CONSTRAINT "transaction_splits_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transaction_splits" ADD CONSTRAINT "transaction_splits_participant_id_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."participants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_import_batch_id_import_batches_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_duplicate_of_id_transactions_id_fk" FOREIGN KEY ("duplicate_of_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "account_balance_snapshots_account_as_of_currency_uq" ON "account_balance_snapshots" USING btree ("account_id","as_of","currency");--> statement-breakpoint
CREATE INDEX "account_balance_snapshots_user_as_of_idx" ON "account_balance_snapshots" USING btree ("user_id","as_of");--> statement-breakpoint
CREATE UNIQUE INDEX "accounts_user_kind_inst_last4_name_uq" ON "accounts" USING btree ("user_id","kind","institution","last4","name");--> statement-breakpoint
CREATE UNIQUE INDEX "bank_accounts_connection_provider_account_uq" ON "bank_accounts" USING btree ("connection_id","provider_account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bank_connections_user_provider_enrollment_uq" ON "bank_connections" USING btree ("user_id","provider","enrollment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "categories_user_name_uq" ON "categories" USING btree ("user_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "counterparty_ignores_user_kind_normalized_uq" ON "counterparty_ignores" USING btree ("user_id","kind","normalized");--> statement-breakpoint
CREATE UNIQUE INDEX "holding_snapshots_account_position_as_of_uq" ON "holding_snapshots" USING btree ("investment_account_id","position_key","as_of");--> statement-breakpoint
CREATE INDEX "holding_snapshots_user_as_of_idx" ON "holding_snapshots" USING btree ("user_id","as_of");--> statement-breakpoint
CREATE UNIQUE INDEX "investment_accounts_user_provider_external_uq" ON "investment_accounts" USING btree ("user_id","provider","external_id");--> statement-breakpoint
CREATE UNIQUE INDEX "investment_transactions_account_external_uq" ON "investment_transactions" USING btree ("investment_account_id","external_id");--> statement-breakpoint
CREATE INDEX "investment_transactions_user_date_idx" ON "investment_transactions" USING btree ("user_id","date");--> statement-breakpoint
CREATE UNIQUE INDEX "jobs_user_name_uq" ON "jobs" USING btree ("user_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "merchant_rules_user_merchant_uq" ON "merchant_rules" USING btree ("user_id","merchant");--> statement-breakpoint
CREATE UNIQUE INDEX "participant_identities_user_kind_normalized_uq" ON "participant_identities" USING btree ("user_id","kind","normalized");--> statement-breakpoint
CREATE INDEX "participant_identities_participant_idx" ON "participant_identities" USING btree ("participant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "participants_user_name_uq" ON "participants" USING btree ("user_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "plaid_link_sessions_link_token_uq" ON "plaid_link_sessions" USING btree ("link_token");--> statement-breakpoint
CREATE INDEX "plaid_link_sessions_user_status_idx" ON "plaid_link_sessions" USING btree ("user_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "securities_user_provider_external_uq" ON "securities" USING btree ("user_id","provider","external_id");--> statement-breakpoint
CREATE UNIQUE INDEX "settlement_items_settlement_tx_uq" ON "settlement_items" USING btree ("settlement_id","transaction_id");--> statement-breakpoint
CREATE INDEX "settlement_items_participant_idx" ON "settlement_items" USING btree ("participant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "transaction_splits_tx_participant_uq" ON "transaction_splits" USING btree ("transaction_id","participant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "transactions_user_dedup_key_uq" ON "transactions" USING btree ("user_id","dedup_key");--> statement-breakpoint
CREATE INDEX "transactions_user_occurred_at_idx" ON "transactions" USING btree ("user_id","occurred_at");--> statement-breakpoint
CREATE INDEX "transactions_user_occurred_on_idx" ON "transactions" USING btree ("user_id","occurred_on");--> statement-breakpoint
CREATE UNIQUE INDEX "user_settings_user_key_uq" ON "user_settings" USING btree ("user_id","key");--> statement-breakpoint
-- Inserts that leave occurred_on empty (core always sets it) fall back to the source's own date, as the SQLite
-- trigger of migration 0008 did (migrations-sqlite/).
CREATE FUNCTION "transactions_occurred_on_default"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."occurred_on" = '' THEN
    NEW."occurred_on" := substr(NEW."occurred_at", 1, 10);
  END IF;
  RETURN NEW;
END
$$;--> statement-breakpoint
CREATE TRIGGER "transactions_occurred_on_default" BEFORE INSERT ON "transactions"
  FOR EACH ROW EXECUTE FUNCTION "transactions_occurred_on_default"();
