-- IBKR Flex NAV in Base: one total per investment account and day (text columns COLLATE "C", added by hand).
CREATE TABLE "investment_daily_nav" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "investment_daily_nav_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"investment_account_id" integer NOT NULL,
	"as_of" text COLLATE "C" NOT NULL,
	"total_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"raw" text COLLATE "C",
	"created_at" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL
);
--> statement-breakpoint
ALTER TABLE "investment_daily_nav" ADD CONSTRAINT "investment_daily_nav_investment_account_id_investment_accounts_id_fk" FOREIGN KEY ("investment_account_id") REFERENCES "public"."investment_accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "investment_daily_nav_account_as_of_uq" ON "investment_daily_nav" USING btree ("investment_account_id","as_of");--> statement-breakpoint
CREATE INDEX "investment_daily_nav_user_as_of_idx" ON "investment_daily_nav" USING btree ("user_id","as_of");