-- Provisional rows: one capture per pasted card SMS, and transactions.provisional on rows no statement has confirmed
-- yet (text columns COLLATE "C", added by hand).
CREATE TABLE "captures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "captures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"kind" text COLLATE "C" NOT NULL,
	"state" text COLLATE "C" NOT NULL,
	"review" text COLLATE "C",
	"dedup_key" text COLLATE "C" NOT NULL,
	"transaction_id" integer,
	"authority_id" integer,
	"occurred_at" text COLLATE "C" NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" text COLLATE "C" NOT NULL,
	"last4" text COLLATE "C",
	"hold" boolean DEFAULT false NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" text COLLATE "C" NOT NULL,
	"updated_at" text COLLATE "C" NOT NULL,
	"resolved_at" text COLLATE "C"
);
--> statement-breakpoint
ALTER TABLE "transactions" ADD COLUMN "provisional" text COLLATE "C";--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_authority_id_transactions_id_fk" FOREIGN KEY ("authority_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "captures_user_dedup_key_uq" ON "captures" USING btree ("user_id","dedup_key");--> statement-breakpoint
CREATE INDEX "captures_user_state_idx" ON "captures" USING btree ("user_id","state");--> statement-breakpoint
CREATE INDEX "captures_transaction_idx" ON "captures" USING btree ("transaction_id");--> statement-breakpoint
CREATE INDEX "captures_authority_idx" ON "captures" USING btree ("authority_id");--> statement-breakpoint
-- Backfill (idempotent: a capture per SMS row by its dedup key, the updates only touch rows not done yet). The state
-- follows the row's current link: it points at another row → superseded by it; an ICBC PDF, Alipay or WeChat row
-- points at it → confirmed by that row; neither → provisional. A pre-authorisation (预授权, from the raw alert) is a
-- hold. Totals do not move here: holds stop counting only through the app's spending rule.
INSERT INTO "captures" ("user_id", "kind", "state", "dedup_key", "transaction_id", "authority_id", "occurred_at", "amount_minor", "currency", "last4", "hold", "payload", "created_at", "updated_at", "resolved_at")
SELECT
  t."user_id",
  'sms',
  s."state",
  t."dedup_key",
  t."id",
  coalesce(t."duplicate_of_id", c."id"),
  t."occurred_at",
  t."amount_minor",
  t."currency",
  coalesce(substring(t."payment_method" from '\((\d{4})\)$'), a."last4"),
  coalesce(t."raw"->>'summary', '') LIKE '预授权%' OR coalesce(t."raw"->>'merchant', '') LIKE '预授权%',
  jsonb_build_object('v', 1, 'history', jsonb_build_array(jsonb_build_object('at', s."now", 'from', NULL, 'to', s."state", 'by', 'migration')))
    || CASE WHEN s."state" = 'provisional' AND t."raw"->>'text' IS NOT NULL THEN jsonb_build_object('text', t."raw"->'text') ELSE '{}'::jsonb END,
  t."created_at",
  s."now",
  CASE WHEN s."state" = 'provisional' THEN NULL ELSE s."now" END
FROM "transactions" AS t
LEFT JOIN "accounts" AS a ON a."id" = t."account_id"
LEFT JOIN LATERAL (
  SELECT o."id" FROM "transactions" AS o
  WHERE o."user_id" = t."user_id" AND o."duplicate_of_id" = t."id" AND o."source" IN ('icbc_pdf', 'alipay', 'wechat')
  ORDER BY o."id"
  LIMIT 1
) AS c ON true
CROSS JOIN LATERAL (
  SELECT
    CASE WHEN t."duplicate_of_id" IS NOT NULL THEN 'superseded' WHEN c."id" IS NOT NULL THEN 'confirmed' ELSE 'provisional' END AS "state",
    to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS "now"
) AS s
WHERE t."source" = 'sms'
ON CONFLICT ("user_id", "dedup_key") DO NOTHING;--> statement-breakpoint
UPDATE "transactions" AS t
SET "provisional" = CASE WHEN c."hold" THEN 'hold' ELSE 'capture' END
FROM "captures" AS c
WHERE c."transaction_id" = t."id" AND c."state" = 'provisional' AND t."provisional" IS NULL;--> statement-breakpoint
-- A hold alert used to be read with the merchant "预授权额度冻结": it names no shop, so blank it (unless edited since).
UPDATE "transactions" AS t
SET
  "merchant" = CASE WHEN t."merchant" LIKE '预授权%' THEN '' ELSE t."merchant" END,
  "counterparty_raw" = '',
  "description_raw" = '预授权额度冻结',
  "source_category" = '预授权额度冻结'
FROM "captures" AS c
WHERE c."transaction_id" = t."id" AND c."hold" AND t."counterparty_raw" LIKE '预授权%';
